<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Await</title>
</head>

<body>
    <h1>Await</h1>
    <script>

        function cuadradoPromise(value) {
            if (typeof value !== "number") {
                return Promise.reject(`Error, el valor "${value}" no es un nÃºmero`);
            }
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve({
                        value: value,
                        result: value * value
                    });
                }, 0 | Math.random() * 1000);
            });
        }

        async function funcionAsincronaDeclarada() {
            try {
                console.log("Inicio de async function d");
                let obj = await cuadradoPromise(0);
                console.log(`Async Function: ${obj.value}, ${obj.result}`);

                obj = await cuadradoPromise(1);
                console.log(`Async Function: ${obj.value}, ${obj.result}`);

                obj = await cuadradoPromise(2);
                console.log(`Async Function: ${obj.value}, ${obj.result}`);

                obj = await cuadradoPromise("a");
                console.log(`Async Function: ${obj.value}, ${obj.result}`);

                obj = await cuadradoPromise(4);
                console.log(`Async Function: ${obj.value}, ${obj.result}`);

                obj = await cuadradoPromise(5);
                console.log(`Async Function: ${obj.value}, ${obj.result}`);
                console.log("Fin de async function d");
            } catch (err) {
                console.error(err);
            }
        }

        funcionAsincronaDeclarada();

        const funcionAsincronaExpresada = async () => {
            try {
                console.log("Inicio de async function e");
                let obj = await cuadradoPromise(6);
                console.log(`Async Function: ${obj.value}, ${obj.result}`);

                obj = await cuadradoPromise(7);
                console.log(`Async Function: ${obj.value}, ${obj.result}`);

                obj = await cuadradoPromise(8);
                console.log(`Async Function: ${obj.value}, ${obj.result}`);

                obj = await cuadradoPromise(9);
                console.log(`Async Function: ${obj.value}, ${obj.result}`);

                obj = await cuadradoPromise(10);
                console.log(`Async Function: ${obj.value}, ${obj.result}`);

                obj = await cuadradoPromise(10);
                console.log(`Async Function: ${obj.value}, ${obj.result}`);
                console.log("Fin de async function e");
            } catch (err) {
                console.error(err);
            }
        }

        funcionAsincronaExpresada();

    </script>
</body>

</html>